services:
  # A Docker web service
  - type: web
    name: scan-crawler-bot
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 5000